### ISSUE TITLE
Fix the text overflowing out of sight in .txt to .pdf conversion

### ISSUE THREAD

**Issue by suraj-singh12** [suraj-singh12/any-to-pdf#1]
### Summary
When a `.txt` file conversion is done to `.pdf`, the contents get written out of the pdf page. 
Need to fix this thing, so that all the information is printed in the visible area of the pdf.

**To do this is :**
Modify the Text2Pdf() function, so that it prints the text on the pdf in a manner that text does not get written out of sight.

**Ensure**:
- [x] Only update the above-mentioned function
- [x] Use comments to describe what you doing in code
- [x] The fix does not break other functionality of the tool

**Comment by rider577** [comment]
May i work on this?

**Comment by suraj-singh12** [comment]
yes @rider577
