### ISSUE TITLE
Adding GUI along with multiple items support

### ISSUE THREAD

**Issue by suraj-singh12** [suraj-singh12/any-to-pdf#5]
The tool is good at its working, but an interactive interface can make it better, easier, and simpler to use.
This issue is open for adding a simple GUI for the any-to-pdf tool.
Your ideas are welcome and feel free to ask any doubt regarding this.

**Comment by UbadahJ** [comment]
@suraj-singh12 How do you want the GUI to be done? Just a simple text field with a path (can have a button to select a file) and pass it to the app?
![image](https://user-images.githubusercontent.com/26687928/135709949-f9290217-fea9-41c2-b28b-1e1036095b24.png)
Something like this maybe?

**Comment by suraj-singh12** [comment]
Somewhat like this @UbadahJ : 
![Screenshot (168)](https://user-images.githubusercontent.com/71935307/135714088-0dd0f0a0-d65e-43e9-8ceb-ba108f4b9283.png)

**Comment by UbadahJ** [comment]
@suraj-singh12 So you want to add support for multiple items too?

**Comment by suraj-singh12** [comment]
pardon, I forgot to add one element to it, I will comment the screenshot again.
Yeah, multiple items support

**Comment by suraj-singh12** [comment]
Yeah, something like this one:
![Screenshot (170)](https://user-images.githubusercontent.com/71935307/135714300-d1f2ea0b-1ab7-4c30-8ec9-0359d65fce22.png)

**Comment by UbadahJ** [comment]
You can modify the title to GUI along with multiple items support and assign me this

**Comment by suraj-singh12** [comment]
Hope title suits now @UbadahJ 
I am assigning it to you.

**Comment by UbadahJ** [comment]
![image](https://user-images.githubusercontent.com/26687928/135724476-cf7daf51-854e-4395-a91e-acac3d9354c2.png)

Made a very minimalist design, so let me know your thoughts

**Comment by suraj-singh12** [comment]
yeah, it's a good starting. 
If you can add one ```About``` button by the left-hand side of ```Quit```, it would be fine then.
Clicking this button a blank Dialog box should pop up, I will populate it later.

**Comment by UbadahJ** [comment]
@suraj-singh12 Review the pull request #6
